package main

var translationsDe = map[messageKey]string{
	msgMultipleResults:                   "Mehrere Ergebnisse gefunden (zeige %d von %d) [Quelle: %s]:",
	msgSelectPrompt:                      "Bitte eine Nummer auswählen (Standard 1, q=beenden, r=suche anpassen): ",
	msgRefinePrompt:                      "Neuen Suchbegriff eingeben: ",
	msgSearchTermEmpty:                   "Suchbegriff darf nicht leer sein.",
	msgInvalidSelection:                  "Ungültige Auswahl. Bitte eine Zahl zwischen 1 und %d eingeben.",
	msgArticleNotFoundAlt:                "Artikel nicht gefunden. Anderes Ergebnis (a), Suche anpassen (r) oder beenden (q)? ",
	msgArticleNotFoundNoAlt:              "Artikel nicht gefunden. Suche anpassen (r) oder beenden (q)? ",
	msgNoOtherResults:                    "Keine weiteren Ergebnisse verfügbar.",
	msgInvalidChoice:                     "Ungültige Auswahl.",
	msgWarningConfigLoad:                 "Warnung: Konfiguration konnte nicht geladen werden: %v",
	msgConfigPersistWarning:              "Warnung: Korrigierte Konfiguration konnte nicht gespeichert werden: %v",
	msgUsage:                             "Verwendung: wikr [Optionen] <Suchbegriff>\n\n",
	msgOptions:                           "Optionen:\n",
	msgFlagLang:                          "Sprache der Wikipedia (en|de)",
	msgFlagSource:                        "Quelle (wikipedia|grokipedia)",
	msgFlagMax:                           "maximale Anzahl der Ergebnisse",
	msgFlagClearCache:                    "Cache leeren",
	msgFlagVersion:                       "Version anzeigen",
	msgFlagResetConfig:                   "Standardkonfiguration neu erstellen und beenden",
	msgErrorWriteDefaultConfig:           "Fehler beim Schreiben der Standardkonfiguration: %v",
	msgConfigReset:                       "Konfiguration auf Standardwerte zurückgesetzt (language=en, max_results=5, source=wikipedia)",
	msgInvalidSource:                     "Ungültige Quelle '%s'. Erlaubt: wikipedia, grokipedia.",
	msgWarningSaveConfig:                 "Warnung: Konfiguration konnte nicht gespeichert werden: %v",
	msgCacheCleared:                      "Cache geleert",
	msgVersion:                           "Version: %s",
	msgChromeNotFoundError:               "Fehler: Chrome/Chromium-Browser nicht gefunden.",
	msgChromeNotFoundDetail:              "Die Grokipedia-Suche erfordert Chrome oder Chromium auf diesem System.",
	msgChromeNotFoundHint:                "Bitte Chrome/Chromium installieren und erneut versuchen, oder '-source wikipedia' verwenden.",
	msgNetworkErrorCacheFallback:         "Netzwerkfehler (%v). Verwende zuvor gespeicherte Suchergebnisse.",
	msgErrorDuringSearch:                 "Fehler bei der Suche: %v",
	msgCachedSearchEmpty:                 "Zwischengespeicherte Suchergebnisse waren leer.",
	msgNoResults:                         "Keine Ergebnisse gefunden.",
	msgSelectionCanceled:                 "Auswahl abgebrochen.",
	msgErrorFetchingSummary:              "Fehler beim Abrufen der Zusammenfassung: %v",
	msgSummaryHeader:                     "Zusammenfassung:",
	msgCachedMarker:                      "(cached)",
	msgURLLabel:                          "URL:",
	msgErrChromeNotFound:                 "Chrome/Chromium-Browser nicht gefunden. Die Grokipedia-Suche erfordert Chrome oder Chromium",
	msgErrCacheDirNotFound:               "Cache-Verzeichnis konnte nicht gefunden werden: %w",
	msgErrCacheDirCreate:                 "Cache-Verzeichnis konnte nicht erstellt werden: %w",
	msgErrConfigDirNotFound:              "Konfigurationsverzeichnis konnte nicht gefunden werden: %w",
	msgErrConfigDirCreate:                "Konfigurationsverzeichnis konnte nicht erstellt werden: %w",
	msgErrDefaultConfigCreate:            "Standardkonfiguration konnte nicht erstellt werden: %w",
	msgErrConfigRead:                     "Konfigurationsdatei %s konnte nicht gelesen werden: %w",
	msgErrConfigDecode:                   "Konfiguration konnte nicht dekodiert werden: %w",
	msgErrConfigEncode:                   "Konfiguration konnte nicht kodiert werden: %w",
	msgErrConfigWrite:                    "Konfigurationsdatei %s konnte nicht geschrieben werden: %w",
	msgErrHTTPCreateRequest:              "Anfrage erstellen: %w",
	msgErrHTTPPerformRequest:             "Anfrage ausführen: %w",
	msgErrHTTPReadBody:                   "Antwort lesen: %w",
	msgErrHTTPTransientStatus:            "Vorübergehender HTTP-Status %d",
	msgErrSearchUnexpectedStatus:         "Unerwarteter Status %d vom Such-Endpunkt",
	msgErrSearchUnexpectedContentType:    "Unerwarteter Content-Type '%s' (erwartet application/json)",
	msgErrSearchDecodeJSON:               "Such-JSON dekodieren: %w",
	msgErrSummaryUnexpectedStatus:        "Unerwarteter Status %d vom Zusammenfassungs-Endpunkt",
	msgErrSummaryUnexpectedContentType:   "Unerwarteter Content-Type '%s'",
	msgErrSummaryDecodeJSON:              "Zusammenfassungs-JSON dekodieren: %w",
	msgErrSummaryMissingExtract:          "Fehlendes 'extract' in der Antwort",
	msgErrSummaryExtractNotString:        "'extract'-Feld ist kein String",
	msgErrSummaryMissingContentURLs:      "content_urls fehlt",
	msgErrSummaryMissingDesktop:          "desktop fehlt in content_urls",
	msgErrSummaryMissingPageURL:          "page URL fehlt",
	msgErrGrokipediaUnexpectedStatus:     "Unerwarteter Status %d von Grokipedia",
	msgErrGrokipediaEmptyTitle:           "Leerer Titel",
	msgErrGrokipediaMissingArticle:       "Artikel '%s' existiert auf Grokipedia noch nicht",
	msgErrGrokipediaMissingArticleSuffix: "existiert auf Grokipedia noch nicht",
	msgErrGrokipediaEmptySearchQuery:     "Leere Suchanfrage",
	msgErrCachePath:                      "Fehler beim Ermitteln des Cache-Pfads: %w",
	msgErrCacheDeleteFile:                "Fehler beim Löschen der Cache-Datei: %v",
}
