package main

var translationsEn = map[messageKey]string{
	msgMultipleResults:                   "Multiple results found (showing %d of %d) [source: %s]:",
	msgSelectPrompt:                      "Select a result number (default 1, q=quit, r=refine): ",
	msgRefinePrompt:                      "Enter new search term: ",
	msgSearchTermEmpty:                   "Search term must not be empty.",
	msgInvalidSelection:                  "Invalid selection. Please enter a number between 1 and %d.",
	msgArticleNotFoundAlt:                "Article not found. Try another (a), refine search (r), or quit (q)? ",
	msgArticleNotFoundNoAlt:              "Article not found. Refine search (r) or quit (q)? ",
	msgNoOtherResults:                    "No other results available.",
	msgInvalidChoice:                     "Invalid choice.",
	msgWarningConfigLoad:                 "Warning: could not load config: %v",
	msgConfigPersistWarning:              "Could not persist corrected config: %v",
	msgUsage:                             "Usage: wikr [options] <search term>\n\n",
	msgOptions:                           "Options:\n",
	msgFlagLang:                          "language of the Wikipedia to use (en|de)",
	msgFlagSource:                        "content source (wikipedia|grokipedia)",
	msgFlagMax:                           "maximum amount of result entries",
	msgFlagClearCache:                    "clear the cache",
	msgFlagVersion:                       "show version",
	msgFlagResetConfig:                   "regenerate default configuration and exit",
	msgErrorWriteDefaultConfig:           "Error writing default config: %v",
	msgConfigReset:                       "Configuration reset to defaults (language=en, max_results=5, source=wikipedia)",
	msgInvalidSource:                     "Invalid source '%s'. Allowed: wikipedia, grokipedia.",
	msgWarningSaveConfig:                 "Warning: could not save config: %v",
	msgCacheCleared:                      "Cache cleared",
	msgVersion:                           "Version: %s",
	msgChromeNotFoundError:               "Error: Chrome/Chromium browser not found.",
	msgChromeNotFoundDetail:              "Grokipedia search requires Chrome or Chromium to be installed on your system.",
	msgChromeNotFoundHint:                "Please install Chrome/Chromium and try again, or use '-source wikipedia' instead.",
	msgChromeNotFoundWarning:             "Warning: Chrome/Chromium not found. Grokipedia search requires Chrome for full functionality.",
	msgChromeNotFoundWarningHint:         "Install Chrome or Chromium to enable full search. Falling back to direct page access.",
	msgNetworkErrorCacheFallback:         "Network error (%v). Using previously cached search results.",
	msgErrorDuringSearch:                 "Error during search: %v",
	msgCachedSearchEmpty:                 "Cached search results were empty.",
	msgNoResults:                         "No results found.",
	msgSelectionCanceled:                 "Selection canceled.",
	msgErrorFetchingSummary:              "Error fetching summary: %v",
	msgSummaryHeader:                     "Summary:",
	msgCachedMarker:                      "(cached)",
	msgURLLabel:                          "URL:",
	msgErrChromeNotFound:                 "Chrome/Chromium browser not found. Grokipedia search requires Chrome or Chromium to be installed",
	msgErrCacheDirNotFound:               "could not find cache directory: %w",
	msgErrCacheDirCreate:                 "could not create cache directory: %w",
	msgErrConfigDirNotFound:              "could not find config directory: %w",
	msgErrConfigDirCreate:                "could not create config directory: %w",
	msgErrDefaultConfigCreate:            "could not create default config: %w",
	msgErrConfigRead:                     "error reading config file %s: %w",
	msgErrConfigDecode:                   "error decoding config: %w",
	msgErrConfigEncode:                   "error encoding config: %w",
	msgErrConfigWrite:                    "error writing config file %s: %w",
	msgErrHTTPCreateRequest:              "create request: %w",
	msgErrHTTPPerformRequest:             "perform request: %w",
	msgErrHTTPReadBody:                   "read body: %w",
	msgErrHTTPTransientStatus:            "transient HTTP status %d",
	msgErrSearchUnexpectedStatus:         "unexpected status %d from search endpoint",
	msgErrSearchUnexpectedContentType:    "unexpected content-type '%s' (expected application/json)",
	msgErrSearchDecodeJSON:               "decode search JSON: %w",
	msgErrSummaryUnexpectedStatus:        "unexpected status %d from summary endpoint",
	msgErrSummaryUnexpectedContentType:   "unexpected content-type '%s'",
	msgErrSummaryDecodeJSON:              "decode summary JSON: %w",
	msgErrSummaryMissingExtract:          "missing 'extract' in response",
	msgErrSummaryExtractNotString:        "'extract' field not a string",
	msgErrSummaryMissingContentURLs:      "missing content_urls",
	msgErrSummaryMissingDesktop:          "missing desktop in content_urls",
	msgErrSummaryMissingPageURL:          "missing page URL",
	msgErrGrokipediaUnexpectedStatus:     "unexpected status %d from Grokipedia",
	msgErrGrokipediaEmptyTitle:           "empty title",
	msgErrGrokipediaMissingArticle:       "article '%s' does not exist on Grokipedia yet",
	msgErrGrokipediaMissingArticleSuffix: "does not exist on Grokipedia yet",
	msgErrGrokipediaEmptySearchQuery:     "empty search query",
	msgErrCachePath:                      "error getting cache path: %w",
	msgErrCacheDeleteFile:                "error deleting cache file: %v",
}
